[package]
name = "sdf-generator"
version = "0.1.1"
description = "A local-first 2D signed distance field generator"
authors = ["xudxud"]
edition = "2021"

[lib]
name = "sdf_generator_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-opener = "2"
